/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calories.and.macros.practice.game;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tetrocs
 */
public class gameScreen extends javax.swing.JFrame {

    /**
     * Creates new form gameScreen
     */
    public gameScreen() {
        initComponents();
    }
    
    public int[] answers = new int[4]; //holds user's answers to the picture
    public boolean[] entry = {false, false, false, false}; //used to check whether user has filled all fields.
    getInfo result;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calorieField = new javax.swing.JTextField();
        calorieLabel = new javax.swing.JLabel();
        carbField = new javax.swing.JTextField();
        carbLabel = new javax.swing.JLabel();
        proteinLabel = new javax.swing.JLabel();
        fatLabel = new javax.swing.JLabel();
        fatField = new javax.swing.JTextField();
        proteinField = new javax.swing.JTextField();
        gameScreenTitle = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        loadedImage = new javax.swing.JLabel();
        servingSizeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calorieField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calorieFieldActionPerformed(evt);
            }
        });

        calorieLabel.setText("Calories");

        carbField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carbFieldActionPerformed(evt);
            }
        });

        carbLabel.setText("Carbohydrates");

        proteinLabel.setText("Protein");

        fatLabel.setText("Fats");

        fatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatFieldActionPerformed(evt);
            }
        });

        proteinField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proteinFieldActionPerformed(evt);
            }
        });

        gameScreenTitle.setText("Guess the macros!");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        loadedImage.setText("Image Loading");

        servingSizeLabel.setText("Per 100g");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(gameScreenTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calorieLabel)
                            .addComponent(carbLabel)
                            .addComponent(proteinLabel)
                            .addComponent(fatLabel)
                            .addComponent(servingSizeLabel))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(carbField)
                            .addComponent(calorieField)
                            .addComponent(fatField)
                            .addComponent(proteinField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 166, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(loadedImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(gameScreenTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(loadedImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(servingSizeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calorieField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calorieLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carbLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proteinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proteinLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fatLabel))
                .addGap(27, 27, 27)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calorieFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calorieFieldActionPerformed
        entry[0] = true;
    }//GEN-LAST:event_calorieFieldActionPerformed

    private void carbFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carbFieldActionPerformed
        entry[1] = true;
    }//GEN-LAST:event_carbFieldActionPerformed

    private void fatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatFieldActionPerformed
        entry[2] = true;
    }//GEN-LAST:event_fatFieldActionPerformed
       
    private void proteinFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proteinFieldActionPerformed
       entry[3] = true; 
    }//GEN-LAST:event_proteinFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        
        //Filling array with answers entered by user into JTextFields
        answers[0] = Integer.parseInt(calorieField.getText()); //retrieving all user submitted information
        answers[1] = Integer.parseInt(carbField.getText());
        answers[2] = Integer.parseInt(proteinField.getText());
        answers[3] = Integer.parseInt(fatField.getText());
        
        //Making sure that the fields are not empty
        boolean filled = true;
        
        for (boolean j: entry ){ //checking if all fields are filled with an answer from user. 
        if (j = false){
            filled = false;
        }
       
        if (!filled){
            System.out.println("One of the fields is not filled.");
        }
        }
        
        //bug catching
        System.out.println("User Answers: ");
        for (int i: answers){
        System.out.println(i);
        }
        System.out.println(new randomizeFood().link); //testing code 
        
        try {
           result = new getInfo(new randomizeFood().link); //object used to scrape data off website
        } catch (IOException ex) {
           Logger.getLogger(gameScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        System.out.println(new scoreCalc(answers, result)); //testing for scoreCalc class
        
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField calorieField;
    private javax.swing.JLabel calorieLabel;
    private javax.swing.JTextField carbField;
    private javax.swing.JLabel carbLabel;
    private javax.swing.JTextField fatField;
    private javax.swing.JLabel fatLabel;
    private javax.swing.JLabel gameScreenTitle;
    private javax.swing.JLabel loadedImage;
    private javax.swing.JTextField proteinField;
    private javax.swing.JLabel proteinLabel;
    private javax.swing.JLabel servingSizeLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
